# Generated by Django 5.2.7 on 2025-10-24 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_list',
            name='status',
            field=models.TextField(choices=[('pasti', 'Pasti'), ('mungkin', 'Mungkin')], default='50%'),
        ),
        migrations.CreateModel(
            name='NobarSpot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('city', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepage_spots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='join_list',
            name='nobar_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='join.nobarspot'),
        ),
        migrations.DeleteModel(
            name='Nobar_Place',
        ),
    ]
