# Generated by Django 5.2.7 on 2025-10-24 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
        ('join', '0002_alter_join_list_status_nobarspot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_list',
            name='nobar_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.nobarspot'),
        ),
        migrations.DeleteModel(
            name='NobarSpot',
        ),
    ]
