# Generated by Django 5.2.7 on 2025-10-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_nobarspot_host'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewers',
            name='nobar_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.nobarspot'),
        ),
        migrations.DeleteModel(
            name='NobarSpot',
        ),
    ]
