# Generated by Django 5.2.7 on 2025-10-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_nobarspot_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewers',
            name='nobar_spot',
        ),
        migrations.RemoveField(
            model_name='reviewers',
            name='user',
        ),
        migrations.DeleteModel(
            name='NobarSpot',
        ),
    ]
