# Generated by Django 5.2.8 on 2025-12-21 14:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0003_alter_nobarspot_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.URLField(blank=True, null=True)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.URLField(blank=True, null=True)),
                ('established_date', models.DateField()),
                ('is_defunct', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('begin_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.competition')),
                ('shownAt', models.ManyToManyField(to='homepage.nobarspot')),
                ('players', models.ManyToManyField(to='match.player')),
            ],
        ),
    ]
