# Generated by Django 5.2.7 on 2025-10-22 11:32

import match.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='logo_height',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AddField(
            model_name='competition',
            name='logo_width',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AddField(
            model_name='players',
            name='logo_height',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AddField(
            model_name='players',
            name='logo_width',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='competition',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', null=True, upload_to=match.models.competition_logo_image_path, width_field='logo_width'),
        ),
        migrations.AlterField(
            model_name='players',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', null=True, upload_to=match.models.player_logo_image_path, width_field='logo_width'),
        ),
    ]
