# Generated by Django 5.2.7 on 2025-10-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_competition_logo_height_competition_logo_width_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
    ]
