# Generated by Django 5.2.7 on 2025-11-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_rename_players_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='logo_height',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='logo_width',
        ),
        migrations.RemoveField(
            model_name='player',
            name='logo_height',
        ),
        migrations.RemoveField(
            model_name='player',
            name='logo_width',
        ),
        migrations.AlterField(
            model_name='competition',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_defunct',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
